title: Shamil Hassan
logo: 1736714187736.jpeg
theme: jekyll-theme-minimal

description: >-
  Lead Data Analyst | Power BI | Tableau | SQL | Excel |
  Helping businesses make data-driven decisions with clear, compelling dashboards.
